openapi: 3.0.0
info:
  title: Atra architecture
  description: |
    Professional Architecture portfolio
  version: 1.0.0
tags:
  - name: Users
    description: Users API
  - name: Projects
    description: Projects API
paths:
  /user/create:
    post:
      tags:
        - Users
      description: Create user
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: components/schemas/CreateUserBody.yaml
      responses:
        '201':
          $ref: components/responses/CreateUserResponse.yaml
        '400':
          $ref: components/responses/BadRequestResponse.yaml
        '500':
          $ref: components/responses/InternalErrorResponse.yaml
components:
  responses:
    BadRequestResponse:
      description: Bad request response
      content:
        application/json:
          schema: &ref_0
            $ref: components/schemas/Error.yaml
          example:
            error:
              status: 400
              details: Bad request
    InternalErrorResponse:
      description: Internal error
      content:
        application/json:
          schema: *ref_0
          example:
            error:
              status: 500
              details: Internal error
    CreateUserResponse:
      $ref: components/responses/CreateUserResponse.yaml
  schemas:
    Error:
      type: object
      required:
        - error
      properties:
        status:
          type: integer
          description: Response code
        details:
          type: string
          description: Error details
    CreateUserBody:
      type: object
      properties:
        email:
          type: string
          description: Email.
          nullable: false
          example: email@email.com
        password:
          type: string
          description: Password.
          nullable: false
          example: 12asj23
        direction:
          type: string
          description: Direction.
          nullable: false
          example: C/ San benito N 10-B
        phone:
          type: number
          description: Phone number.
          nullable: false
          example: 679123046
        image:
          type: string
          format: binary
          description: User image.
          nullable: false
          example: ''

