openapi: 3.0.0
info:
  title: Atra architecture
  description: |
    Professional Architecture portfolio
  version: 1.0.0
tags:
  - name: Users
    description: Users API
  - name: Projects
    description: Projects API
paths:
  /user/create:
    $ref: paths/users/user_create.yaml
components:
  responses:
    BadRequestResponse:
      $ref: components/responses/BadRequestResponse.yaml
    InternalErrorResponse:
      $ref: components/responses/InternalErrorResponse.yaml
    CreateUserResponse:
      $ref: components/responses/CreateUserResponse.yaml
  schemas:
    Error:
      $ref: components/schemas/Error.yaml
    CreateUserBody:
      $ref: components/schemas/CreateUserBody.yaml

