openapi: 3.0.0

info:
  title: Atra architecture
  description: |
    Professional Architecture portfolio
  version: 1.0.0

tags:
  - name: Users
    description: Users API

  - name: Projects
    description: Projects API

  - name: Auth
    description: Auth API

paths:
  $ref: './paths/_index.yaml'

components:
  $ref: './components/_index.yaml'
