type: object
required:
  - id
  - title
  - description
  - year
  - isTop
  - createdAt
  - updatedAt
  - mainImage
  - images
properties:
  id:
    type: string
    description: 'The unique identifier for the project.'
    nullable: false
    example: 'fb8f6e09-d550-4358-a288-222406c594cb'
  title:
    type: string
    description: "The project's title."
    nullable: false
    example: 'Project title'
  description:
    type: string
    description: "The project's description."
    nullable: false
    example: 'Project description'
  year:
    type: number
    description: "The project's year."
    nullable: false
    example: 2012
  isTop:
    type: boolean
    description: 'Flag of project top.'
    nullable: false
    example: true
  createdAt:
    type: string
    format: date-time
    description: 'The timestamp when the project was created.'
    nullable: false
    example: '2024-01-10T19:14:04.489431Z'
  updatedAt:
    type: string
    format: date-time
    description: 'The timestamp when the project was updated.'
    nullable: false
    example: '2024-01-10T19:14:04.489431Z'
  mainImage:
    type: string
    description: 'The main image url.'
    nullable: false
    example: 'project/main.webp-5bab0fbc-93ac-4bda-be69-af67fc9c2a54'
  images:
    type: array
    items:
      type: string
      description: 'The image url.'
      nullable: false
      example: 'project/1.webp-5bab0fbc-93ac-4bda-be69-af67fc9c2a54'
