type: object
required:
  - id
  - title
  - description
  - year
  - isTop
  - createdAt
  - updatedAt
  - mainImage
  - images
properties:
  id:
    type: string
    description: 'The unique identifier for the project.'
    nullable: false
    example: '615175183151032984302'
  title:
    type: string
    description: "The project's title."
    nullable: false
    example: 'Project title'
  description:
    type: string
    description: "The project's description."
    nullable: false
    example: 'Project description'
  year:
    type: number
    description: "The project's year."
    nullable: false
    example: 2012
  isTop:
    type: boolean
    description: 'Flag of project top.'
    nullable: false
    example: true
  createdAt:
    type: string
    format: date-time
    description: 'The timestamp when the project was created.'
    nullable: false
    example: '2024-01-10T19:14:04.489431Z'
  updatedAt:
    type: string
    format: date-time
    description: 'The timestamp when the project was updated.'
    nullable: false
    example: '2024-01-10T19:14:04.489431Z'
  mainImage:
    $ref: 'components/_index.yaml#/schemas/File'
  images:
    type: array
    items:
      $ref: 'components/_index.yaml#/schemas/File'
