name: Atra architecture CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**.js'
      - 'frontend/**.jsx'
      - 'frontend/**.ts'
      - 'frontend/**.tsx'
      - 'frontend/**.yml'
      - 'frontend/**.json'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  install-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('frontend/**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pnpm install
        working-directory: ./frontend
  lint-format:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Run lint
        run: pnpm lint
        working-directory: ./frontend
      - name: Run prettier
        run: pnpm format
        working-directory: ./frontend
  type-check:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Check types
        run: pnpm type-check
        working-directory: ./frontend
  build:
    runs-on: ubuntu-latest
    needs: [lint-format, type-check]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Run build
        run: pnpm build
        working-directory: ./frontend
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: frontend/.next
          retention-days: 1
