name: Atra architecture Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**.js'
      - 'frontend/**.ts'
      - 'frontend/**.json'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  install-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Cache Playwright binary
        id: cache-playwright-binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Playwright
          key: playwright-binary-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            playwright-binary-
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          cd frontend && pnpm install
  lint-format:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Restore pnpm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Run lint
        run: |
          cd frontend && pnpm lint
      - name: Run prettier
        run: |
          cd frontend && pnpm format
  type-check:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Restore pnpm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Check types
        run: |
          cd frontend && pnpm type-check
  build:
    runs-on: ubuntu-latest
    needs: [lint-format, type-check]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Restore pnpm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Run build
        run: |
          cd frontend && pnpm build
  e2e-tests-chrome:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Restore pnpm dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Restore Playwright binary
        id: cache-playwright-binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Playwright
          key: playwright-binary-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            playwright-binary-
      - name: Run Tests
        shell: bash
        run: cd frontend && pnpm run test:e2e
